---
# tasks file for create_inventory

- name: Create a Inventory
  uri:
    url: "https://3.236.84.49/api/v2/inventories/"
    validate_certs: no
    force_basic_auth: true
    method: POST
    user: "admin"
    password: "password"
    return_content: yes 
    headers: 
      Content-Type: "application/json"
    body_format: json
    body: "{ \"kind\" : \"\", \"name\" : \"auto_inventory_1\", \"organization\" : 1 }"
  register: result 
  
- debug:
    msg: result
